2020-01-14 16:59:40.748949
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 828, in _resolve_lookup
    current = current[bit]
TypeError: 'AptitudeSet' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 172, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\fields\mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'fk_sections'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\aptitude\views.py", line 72, in aptitude_test
    "faculty_obj": faculty_obj})
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 302, in render
    match = condition.eval(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\defaulttags.py", line 876, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 186, in __get__
    rel_obj = self.get_object(instance)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 153, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')


2020-01-14 16:59:49.577748
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 199, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\mysql\base.py", line 233, in get_new_connection
    return Database.connect(**conn_params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on '3.6.127.100' (10060)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\aptitude\views.py", line 38, in aptitude_test
    session = request.session.get('user_id')
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 75, in get
    return self._session.get(key, default)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1135, in execute_sql
    cursor = self.connection.cursor()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 260, in cursor
    return self._cursor()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 236, in _cursor
    self.ensure_connection()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\db\backends\mysql\base.py", line 233, in get_new_connection
    return Database.connect(**conn_params)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '3.6.127.100' (10060)")


2020-01-14 17:38:24.716145
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\aptitude\views.py", line 273, in edit_master_aptitude_details
    "edit_view": edit_view})
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 652: 'static'. Did you forget to register or load this tag?


2020-01-14 17:38:30.235836
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\aptitude\views.py", line 273, in edit_master_aptitude_details
    "edit_view": edit_view})
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 652: 'static'. Did you forget to register or load this tag?


2020-01-14 17:39:30.112279
Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS\New folder\tripude_cms\aptitude\views.py", line 273, in edit_master_aptitude_details
    "edit_view": edit_view})
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\CMS\New folder\tripude_cms\venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 988: 'static'. Did you forget to register or load this tag?


